//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub use super::eggs::Entity as Eggs;
pub use super::locations::Entity as Locations;
pub use super::nests::Entity as Nests;
pub use super::nodes::Entity as Nodes;
pub use super::servers::Entity as Servers;
pub use super::users::Entity as Users;
