[workspace]
resolver = "2"
members = [
    "crates/webserver",
    "crates/webserver/migration",
    "crates/webserver/entity",
    "crates/daemon",
]
default-members = ["crates/webserver", "crates/daemon"]
