[workspace]
resolver = "2"
members = [
    "crates/webserver",
    "crates/webserver/migration",
    "crates/webserver/entity",
    "crates/daemon",
]
default-members = ["crates/webserver", "crates/daemon"]

[profile.release]
debug = false
lto = true
strip = true
codegen-units = 1
opt-level = 3