version = 1

[web-server]
url = "https://panel.example.com/"
bind-address = "127.0.0.1"
port = 8080

[debug]
log-level = "info"

[postgres]
ip = "127.0.0.1"
port = 5432
schema = "triceratops"
username = "triceratops_panel"
password = "CHANGEME"

[redis]
ip = "127.0.0.1"
port = 6379

[auth]
jwt-secret = "CHANGEME"