version = 1

[web-server]
url = "http://localhost:8080/"
bind-address = "0.0.0.0"
port = 8080
headless = false

[debug]
log-level = "info"

[postgres]
ip = "127.0.0.1"
port = 5432
schema = "triceratops"
username = "username"
password = "password"

[redis]
ip = "127.0.0.1"
port = 6379
password = "password"

[auth.oauth.custom]
client-id = "Password1"
client-secret = "Password1"
discovery-url = "https://example.com/.well-known/openid-configuration"
scopes = ["openid", "profile", "email"]

[auth.oauth.discord]
client-id = "Password1"
client-secret = "Password1"

[auth.oauth.google]
client-id = "Password1"
client-secret = "Password1"

[auth.oauth.microsoft]
client-id = "Password1"
client-secret = "Password1"
tenant-id = "b32229b0-a29a-41ca-bf91-af2fe5182c5e"

[auth.oauth.okta]
client-id = "Password1"
client-secret = "Password1"

[auth.oauth.whmcs]
client-id = "Password1"
client-secret = "Password1"

[auth.saml]
sso_url = "https://example.com/"
issuer = "ACME Corp"
signing-certificate = "super secure cert"
