[web_server]
bind-address = "0.0.0.0"
port = 8080

[postgres]
ip = "127.0.0.1"
port = 5432
schema = "triceratops"
username = "triceratops"

[redis]
ip = "127.0.0.1"
port = 6379

[auth.oauth.discord]
client-id = "Password1"
client-secret = "Password1"

[auth.oauth.microsoft]
client-id = "Password1"
client-secret = "Password1"
tenant-id = "b32229b0-a29a-41ca-bf91-af2fe5182c5e"

[auth.saml]
sso_url = "https://example.com/"
issuer = "ACME Corp"
signing_certificate = "super secure cert"
