version = 1

[web-server]
bind-address = "127.0.0.1"
headless     = false
port         = 8080
url          = "http://localhost:8080/"

[debug]
log-level = "info"

[postgres]
ip       = "127.0.0.1"
password = "Password1"
port     = 5432
schema   = "triceratops"
username = "username"

[redis]
expiry   = 300
ip       = "127.0.0.1"
password = "Password1"
port     = 6379

[auth]
jwt-secret = "Password1"

[auth.oauth.discord]
client-id     = "Password1"
client-secret = "Password1"

[auth.oauth.microsoft]
client-id     = "Password1"
client-secret = "Password1"
tenant-id     = "b32229b0-a29a-41ca-bf91-af2fe5182c5e"

