version: "3"

services:
  postgres:
    image: postgres:16.1
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=triceratops

  redis:
    image: eqalpha/keydb:x86_64_v6.3.4 # Uncomment this line when using anything but Mx Mac
    # image: eqalpha/keydb:arm64_v6.3.4 # This works on my Mac, don't come at me.
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:
