version: "3"

services:
  postgres:
    image: postgres:16.1
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=triceratops

  redis:
    image: eqalpha/keydb:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:
