[package]
name = "triceratops-server"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
triceratops-server-migration = { path = "./migration" }
triceratops-server-entity = { path = "./entity" }

axum = { version = "0.6.20", features = ["ws", "http2", "headers"] }
axum-extra = "0.8.0"
clap = "4.4.8"
redis = { version = "0.23.3", features = ["tokio-comp", "connection-manager"] }
sea-orm = { version = "0.12.6", features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "with-chrono",
] }
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
tokio = { version = "1.34.0", features = [
    "sync",
    "macros",
    "rt-multi-thread",
    "tracing",
] }
cuid2 = "0.1.2"
dotenvy = "0.15.7"
mobc = "0.8.3"
mobc-redis = "0.8.2"
zeroize = { version = "1.7.0", features = [
    "serde",
    "derive",
    "std",
    "aarch64",
] }
rand = { version = "0.8.5", features = ["serde"] }
rand_core = { version = "0.6.4", features = ["std", "serde"] }
argon2 = { version = "0.5.2", features = ["std", "zeroize"] }
chrono = { version = "0.4.31", features = ["serde"] }
