[package]
name = "triceratops-server"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.20", features = ["ws", "http2", "headers"] }
axum-extra = "0.8.0"
clap = "4.4.8"
redis = "0.23.3"
sea-orm = { version = "0.12.6", features = ["sqlx-postgres", "runtime-tokio-rustls", "with-chrono"] }
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
tokio = { version = "1.34.0", features = ["sync", "macros", "rt-multi-thread", "tracing"] }
